[llvm]
ninja = false

[build]
python = "python2.7"
extended = true
# Verbosity level: 0 == not verbose, 1 == verbose, 2 == very verbose
verbose = 0
# Build the sanitizer runtimes
#sanitizers = false

[install]
prefix = "/usr"
sysconfdir = "/etc"
libdir = "/usr/lib"
docdir = "/usr/share/doc/rust"
mandir = "/usr/share/man"

[rust]
codegen-units = 0
debuginfo = true

# Whether or not line number debug information is emitted
#debuginfo-lines = false

channel = "stable"
